### ISSUE TITLE
Options for escaping url attributes

### ISSUE THREAD

**Issue by jacomensink** [justin713/gulp-premailer#6]
Is it possible to create an option for escaping url attributes?
Premailer supports `escape_url_attributes:false`. Is it possible to add this option in `gulp-premailer`?

**Comment by jfmaeck** [comment]
I would very much appreciate this option, too.

**Comment by justin713** [comment]
Hi @jacomensink and @jfmaeck: Sorry it has taken so long to respond.

After looking into adding this feature -- and I could very well be wrong about this -- it appears that some options are not available via CLI. Specifically, `escape_url_attributes` is available when used in Ruby, but [according to the documentation](https://github.com/premailer/premailer/wiki/Premailer-Command-Line-Usage), that option is not available to us here.

Again, I could be wrong, and if so, please let me know.

**Comment by jfmaeck** [comment]
Hi @justin713 ,

I came to the same conclusion. Sorry for bothering you and thanks for looking into it.

**Comment by justin713** [comment]
@jfmaeck No worries. I also expected option parity using CLI. If and when further option support is added, I'll do so as well.
